# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Mediation_Ordered_Multi_Merr_cpp <- function(X, m_star, y_star, k_M, k_Y, M_ind, Y_ind, A_M, betabar, Ad_M, s_M, inc_root_M, dstarbar_M, betahat, A_Y, beta_2_bar, Ad_Y, s_Y, inc_root_Y, dstarbar_Y, beta_2_hat, R, keep, nprint) {
    .Call(`_BFMediate_Mediation_Ordered_Multi_Merr_cpp`, X, m_star, y_star, k_M, k_Y, M_ind, Y_ind, A_M, betabar, Ad_M, s_M, inc_root_M, dstarbar_M, betahat, A_Y, beta_2_bar, Ad_Y, s_Y, inc_root_Y, dstarbar_Y, beta_2_hat, R, keep, nprint)
}

runiregGibbs_betafix <- function(y, X, betabar, A, nu, ssq, sigmasq, R, keep, nprint, betafix) {
    .Call(`_BFMediate_runiregGibbs_betafix`, y, X, betabar, A, nu, ssq, sigmasq, R, keep, nprint, betafix)
}

breg_me <- function(y, X, betabar, A) {
    .Call(`_BFMediate_breg_me`, y, X, betabar, A)
}

rtrun <- function(mu, sigma, a, b) {
    .Call(`_BFMediate_rtrun`, mu, sigma, a, b)
}

dstartoc <- function(dstar) {
    .Call(`_BFMediate_dstartoc`, dstar)
}

lldstar <- function(dstar, y, mu, ssq_y_tilde) {
    .Call(`_BFMediate_lldstar`, dstar, y, mu, ssq_y_tilde)
}

dstarRwMetrop <- function(y, mu, olddstar, s, inc_root, dstarbar, rootdi, ncut, ssq_y_tilde) {
    .Call(`_BFMediate_dstarRwMetrop`, y, mu, olddstar, s, inc_root, dstarbar, rootdi, ncut, ssq_y_tilde)
}

dstarRwMetrop_1 <- function(y, mu, olddstar, s, inc_root, dstarbar, rootdi, ncut, ssq_y_tilde) {
    .Call(`_BFMediate_dstarRwMetrop_1`, y, mu, olddstar, s, inc_root, dstarbar, rootdi, ncut, ssq_y_tilde)
}

breg2 <- function(root, X, y, Abetabar) {
    .Call(`_BFMediate_breg2`, root, X, y, Abetabar)
}

norm_rs <- function(a, b) {
    .Call(`_BFMediate_norm_rs`, a, b)
}

half_norm_rs <- function(a, b) {
    .Call(`_BFMediate_half_norm_rs`, a, b)
}

unif_rs <- function(a, b) {
    .Call(`_BFMediate_unif_rs`, a, b)
}

exp_rs <- function(a, b) {
    .Call(`_BFMediate_exp_rs`, a, b)
}

rtnm <- function(mus, sigmas, lower, upper) {
    .Call(`_BFMediate_rtnm`, mus, sigmas, lower, upper)
}

rtrunVec <- function(mu, sigma, a, b) {
    .Call(`_BFMediate_rtrunVec`, mu, sigma, a, b)
}

startMcmcTimer <- function() {
    invisible(.Call(`_BFMediate_startMcmcTimer`))
}

infoMcmcTimer <- function(rep, R) {
    invisible(.Call(`_BFMediate_infoMcmcTimer`, rep, R))
}

endMcmcTimer <- function() {
    invisible(.Call(`_BFMediate_endMcmcTimer`))
}

breg1 <- function(root, X, y, Abetabar) {
    .Call(`_BFMediate_breg1`, root, X, y, Abetabar)
}

lndMvn <- function(x, mu, rooti) {
    .Call(`_BFMediate_lndMvn`, x, mu, rooti)
}

rordprobitGibbs_me_M_multi_merr_cpp_loop <- function(dep, y, X, k, A, betabar, Ad, A_2, betabar_2, s, inc_root, dstarbar, betahat, Y_ind, R, keep, nprint) {
    .Call(`_BFMediate_rordprobitGibbs_me_M_multi_merr_cpp_loop`, dep, y, X, k, A, betabar, Ad, A_2, betabar_2, s, inc_root, dstarbar, betahat, Y_ind, R, keep, nprint)
}

rordprobitGibbs_me_multi_merr_cpp_loop <- function(y, X, k, A, betabar, Ad, s, inc_root, dstarbar, betahat, Y_ind, R, keep, nprint) {
    .Call(`_BFMediate_rordprobitGibbs_me_multi_merr_cpp_loop`, y, X, k, A, betabar, Ad, s, inc_root, dstarbar, betahat, Y_ind, R, keep, nprint)
}

startMcmcTimer <- function() {
    invisible(.Call(`_BFMediate_startMcmcTimer`))
}

infoMcmcTimer <- function(rep, R) {
    invisible(.Call(`_BFMediate_infoMcmcTimer`, rep, R))
}

endMcmcTimer <- function() {
    invisible(.Call(`_BFMediate_endMcmcTimer`))
}

runiregGibbs_rcpp_me <- function(y, X, betabar, A, nu, ssq, sigmasq, R, keep, nprint, betafix, sigmafix, betavalue, sigmavalue) {
    .Call(`_BFMediate_runiregGibbs_rcpp_me`, y, X, betabar, A, nu, ssq, sigmasq, R, keep, nprint, betafix, sigmafix, betavalue, sigmavalue)
}

